# version: "3.8"
services:
  # springboot-app
  # nextjs-app
  s3storage:
    image: localstack/localstack:2.3.2
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=aaa
      - AWS_SECRET_ACCESS_KEY=aaa
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - s3storage_volume:/tmp/localstack/s3
      - "./backend/init_s3_data/scripts:/etc/localstack/init/ready.d"
      - "./backend/init_s3_data/data:/home/localstack/data"
  postgresql:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresAdmin
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
volumes:
  postgresql_volume:
  s3storage_volume:
