# version: "3.8"
services:
  # springboot-app
  # nextjs-app
  postgresql:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresAdmin
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
volumes:
  postgresql_volume:
